sym16_simple_stock_ilike:
    path:	/iLike/{verbe}
    defaults: {_controller: SYM16SimpleStockBundle:RAMIPremierControleur:iLike}

sym16_simple_stock_produit:
    path:	/produit/{var1}/{var2}
    defaults: {_controller: SYM16SimpleStockBundle:RAMIPremierControleur:produit}
    requirements:
	var1: ^[0-9a-fA-F]*$
	var2: ^[0-9a-fA-F]*$
